vim.opt.guicursor = ""
vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.tabstop = 4 -- Show existing tab with 4 spaces width
vim.opt.softtabstop = 4 -- Show existing tab with 4 spaces width
vim.opt.shiftwidth = 4 -- When indenting with '>', use 4 spaces width
vim.opt.expandtab = true -- On pressing tab, insert 4 spaces
vim.opt.smarttab = true -- insert tabs on the start of a line according to shiftwidth
vim.opt.smartindent = true -- Automatically inserts one extra level of indentation in some cases
vim.opt.expandtab = true
vim.opt.wrap = false
vim.opt.ignorecase = true -- Ingore case in search
vim.opt.incsearch = true
vim.opt.hlsearch = true
vim.opt.smartcase = true -- Consider case if there is a upper case character
vim.opt.scrolloff = 10 -- Minimum number of lines to keep above and below the cursor
vim.opt.colorcolumn = "120" -- Draws a line at the given line to keep aware of the line size
vim.opt.signcolumn = "yes" -- Add a column on the left. Useful for linting
vim.opt.shell = "/opt/homebrew/bin/zsh"
-- vim.opt.shell = "fish"
vim.opt.cmdheight = 3 -- Give more space for displaying messages
vim.opt.updatetime = 50 -- Time in miliseconds to consider the changes
vim.opt.encoding = "utf-8" -- The encoding should be utf-8 to activate the font icons
vim.opt.backup = false -- No backup files
vim.opt.swapfile = false
-- vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.autoread = true -- Update vim after file update from outside
vim.opt.autowrite = true --
vim.opt.clipboard = "unnamedplus" --macos copy
